# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2025 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

name: Sync and Release

on:
  schedule:
    - cron: "0 0 1 * *" # Run once a month
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: false
        default: 'Manual trigger'

permissions:
  contents: write

jobs:
  check-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run script to update robot and machine lists
        run: |
          cd scripts/ && python update-lists.py && cd ..

      - name: Check for changes
        run: |
          git diff --quiet counter_robots/data/ || echo "changes_detected=true" >> $GITHUB_ENV
        continue-on-error: true

      - name: Commit if changes detected
        if: env.changes_detected == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: 'counter_robots/data/*.txt'
          commit_message: Update robots and machines lists

      - name: Update version
        id: date
        if: env.changes_detected == 'true'
        run: |
          NEW_VERSION=$(date +'%Y.%m')
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV
          sed -i 's/^__version__ = .*/__version__ = '"'"$NEW_VERSION"'"'/' counter_robots/version.py

      - name: Push release commit
        if: env.changes_detected == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: 'counter_robots/version.py'
          commit_message: 'release: ${{ env.new_version }}'

      - name: Create and push tag
        run: |
          git fetch --tags
          git tag "v${{ env.new_version }}" -a "release: ${{ env.new_version }}"
          git push origin "v${{ env.new_version }}"
